export enum RelationRoot {
  ROLE = 'roles',
  USER = 'users',
}
export enum COLLECTION_NAME {
  AUDIT = 'audits',
  CATEGORY = 'categories',
  COLLECTION = 'collections',
  CUSTOM_POST = 'custom-posts',
  FORM_BUILDER = 'form-builder',
  ELEMENT = 'elements',
  TERM = 'terms',
  GROUP_FIELD = 'group-fields',
  GROUP = 'groups',
  FILE = 'files',
  MENU = 'menus',
  MENU_ITEM = 'menu-items',
  PAGE = 'pages',
  PERMISSION = 'permissions',
  POST = 'posts',
  USER_POST = 'user-posts',
  ROLE = 'roles',
  RULE = 'rules',
  SEO_PATH = 'seo-paths',
  SETTING = 'settings',
  TAG_GROUP = 'tag-groups',
  TAG = 'tags',
  TEMPLATE_MAIL = 'template-mail',
  TEMPLATE = 'templates',
  USER = 'users',
}
